version: '3.1'

services:
  mongo1:
    image: mongo
    restart: always
    volumes:
    - ./database/_mongo1:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: test
    ports:
    - 27019:27017

  mongo2:
    image: mongo
    restart: always
    volumes:
    - ./database/_mongo2:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: test
    ports:
    - 27018:27017